### ISSUE TITLE
Centos İnstall

### ISSUE THREAD

**Issue by FatihTasdemir** [viz-centric/flair-bi#301]
Hello, anyone can help about how to install FlairBi on Centos - 8 ?

**Comment by kalyan21** [comment]
Thanks for reaching out to us, Flair BI is operating system agnostic. So it is possible to install Flair BI on Centos. However, Flair is a microservices based architecture, which would mean you would have to deploy multiple services to get it to work and the advantage of this is that you can scale individual services efficiently unlike other BI tools.

The prefered method of deploying Flair is as docker containers and ideally orchestrate it using a platform like Kubernetes. You need to have docker and docker-compose installed.
You can find the documentation on how you can run the application as docker images here: https://github.com/viz-centric/flair-bi/wiki/Quick-start
Also, if you have access to a kubernetes cluster, you can deploy flair as documented here: https://github.com/viz-centric/flair-helm-charts

If you still feel like building and running the application manually, please let us know and we can give further information.

Also, let us know if you are looking for a missing features. We are a very active community and we can try to help you out there!

**Comment by FatihTasdemir** [comment]
Hello,Thank you for your interest,Can you forward the installation steps one by one on Centos 8? so step by step,

like "https://github.com/viz-centric/flair-bi/wiki/Quick-start"  this.. for centos 8...

**Comment by kalyan21** [comment]
Sure, no problem at all. We can create a step by step installation guide for you. 
Can you please let us know which sources you are planning to connect to?

**Comment by FatihTasdemir** [comment]
MSSQL

**Comment by admin-vizcentric** [comment]
Hello, 

We currently don't have a connector for MSSQL,  Below are the list of connectors we support

PostgreSQL
MongoDB
Spark
Kafka
Oracle
Cockroach DB
Mysql
Redshift
Athena

- Connectors in Q1 2020 roadmap

Snowflake
Google BIgquery

- Connectors in Q2 2020 Roadmap

MSSQL

**Comment by admin-vizcentric** [comment]
Dear FatihTasdemir,

Please if you need any further information don't hesitate to contact us on support@vizcentric.com

Closing this issue. 

Best Wishes, 
Vizcentric Support Team
