### ISSUE TITLE
Snowflake Driver

### ISSUE THREAD

**Issue by will-harrison-kindred** [viz-centric/flair-bi#322]
Hi, 

Regarding the Snowflake DWH driver on your road map. 
https://github.com/viz-centric/flair-bi/wiki/Setting-up-connectors#connector-configuration

We would appreciate it work could be prioritised and available before the end of Q1. 

Could you also list which features will be available please. 

There are some details on connecting to Snowflake here. If more information is needed please let me know.  https://docs.snowflake.net/manuals/user-guide-connecting.html

I have followed up with an email.

Thank you.

Best regards,
Will Harrison 
Kindred Group

**Comment by will-harrison-kindred** [comment]
The Snowflake driver will be functionally similar to these drivers, particularly the Redshift one:

https://github.com/viz-centric/flair-bi/wiki/Setting-up-connectors#connector-configuration

**Comment by admin-vizcentric** [comment]
Dear @will-harrison-kindred ,

We plan to release Snowflake Driver 3rd week of December.

**Comment by admin-vizcentric** [comment]
Hi @will-harrison-kindred 

Snowflake connector has been released in December. Can this ticket now be closed? if any issues with connector please let us know .

Thanks,
Vizcentric Team
