### ISSUE TITLE
Sign out is not working

### ISSUE THREAD

**Issue by fabiofilz** [viz-centric/flair-bi#435]
The sign out is not working.

**Comment by admin-vizcentric** [comment]
Hi @fabiofilz,

Thanks for letting us know. We will investigate and get back to you regarding this.

Thanks,
Vizcentric team

**Comment by admin-vizcentric** [comment]
Hi @fabiofilz 

We are not able to replicate the issue you are reporting. Can you tell us what error you are getting? And also please let us know what version of Flair BI you are using.

It would be great if you can provide issue reproducing steps. 

Thanks,
Vizcentric team

**Comment by fabiofilz** [comment]
Hi Vizcentric team,

Once I am logged in the system, I click in the icon in the right top corner, and Sign out, but nothing happens.

image:
  repository: flairbi/flairbi
  tag: v2.2.1-SNAPSHOT.e1a39e43

Kind regards,
Fabio

**Comment by admin-vizcentric** [comment]
Hi @fabiofilz 

Do you see any error logs in Developer Tools > Console logs?  If yes, then please send us the logs.

One other test you could do is once you hit the logout button, click on “New Dashboard” in the QuickStart menu. Does it take you to login page?

We are not able to replicate the error from our side. It could be a routing issue or some backend issues resulting due to configuration in your environment. 

Either way, we will do our best to help you resolve this issue. 

Thanks,
Vizcentric Team

**Comment by admin-vizcentric** [comment]
Hi @fabiofilz ,

Could you let us know the test outcomes based on the above troubleshooting steps. If you are not facing this issue anymore please let us know so we can close this issue.

Thanks,
Kalyan

**Comment by fabiofilz** [comment]
Hi @admin-vizcentric,

Sorry for my late response.

I did the test as requested:

1 - This is the error:
![image](https://user-images.githubusercontent.com/45266582/78037576-a8d96f00-7363-11ea-8e87-47e09947da18.png)

2.1 - I had to click in "sign out"
2.2 - Click in New Dashboard
After it shows the login page, but I am able to see the dashboard without being logged into the application. It also show this error
![image](https://user-images.githubusercontent.com/45266582/78038823-35386180-7365-11ea-90b3-86ca820eb23d.png)

We need to have control of which OKTA group will access each report/dashboard.

Thank you for your help.

Kind regards,
Fabio

**Comment by admin-vizcentric** [comment]
Hey @fabiofilz,
could you share the server logs when You try to log out?

Thank You and Best regards,
Vizcentric Team

**Comment by fabiofilz** [comment]
Hi @admin-vizcentric,

Do you mean the log output from the Flair BI pod?

Kind regards,
Fabio

**Comment by admin-vizcentric** [comment]
Hi @fabiofilz,
Yes the logs that occur when You press logout button.

Best regards,
Vizcentric Team

**Comment by fabiofilz** [comment]
Hi @admin-vizcentric,

When I click on sign out there is no messages in the log output. The message below happens when I click on New Dashboard and the login screen shows up.

Log from the Flair-bi pod.

flair-bi-79659bf7bb-8shn6 flair-bi 2020-04-01 08:11:20.713  INFO 8 --- [trap-executor-0] c.n.d.s.r.aws.ConfigClusterResolver      : Resolving eureka endpoints via configuration

Kind regards,
Fabio

**Comment by fabiofilz** [comment]
Working since last version.
