### ISSUE TITLE
Table order by

### ISSUE THREAD

**Issue by fabiofilz** [viz-centric/flair-bi#497]
The order by defined in the field is not working.

I would like to represent this query in the table:

SELECT kpi_type, field_1, field_2, start_date, end_date, unblended_cost_yesterday, unblended_cost_today, per, currency FROM public.mtd_kpi_daily_vw order by **aggregation_type**, kpi_type, field_1, field_2

1 - Order by: I set the order in each of the field in the "order by" as ascent and it is not reflecting in table. I added the fields in order from the left to the right

2 - Hide a field: I am using a field to order (aggregation_type), but I don't want to see this field in the table

**Expected behavior**
It would show the result of the data ordered by the sequence of the fields used in the order by and  hide the field aggregation_type in the table.

**Screenshots**
![image](https://user-images.githubusercontent.com/45266582/77678142-a43e4080-6f88-11ea-9a6d-f20991b9c38b.png)
![image](https://user-images.githubusercontent.com/45266582/77678227-bcae5b00-6f88-11ea-9411-fd00a5b87912.png)
![image](https://user-images.githubusercontent.com/45266582/77678300-db145680-6f88-11ea-9421-5e5fc862e533.png)

**Desktop (please complete the following information):**
 - MacOS Catalina
 - Google Chrome 
 - Version 80.0.3987.149 (Official Build) (64-bit)

**Additional context**
Docker image running in AWS EKS: image: flairbi/flairbi:v2.4.1-SNAPSHOT.eb12f144

Thank you.
Fabio

**Comment by admin-vizcentric** [comment]
Hi @fabiofilz , 

As I understood, you want to order the dimension by ascending order?

By default except for the first measure which is set to DESC by default. All other fields sorting is set to NONE. 

If you want to sort a Dimension by ascending order than set the first measure sorting to NONE (in your case it is "unblended_cost_yesterday")  then change the sorting order for Dimension to Ascending. 

Best Wishes,
Kalyan

**Comment by fabiofilz** [comment]
Hi @kalyan21,

There are 2 situations:

1 situation - I have 4 columns (Dimensions) that I would like to order in sequence: 
- aggregation_type desc, 
- kpi_type desc, 
- field_1 desc, 
- field_2 desc 

It is the same behavior as "select * from table_name order by aggregation_type, kpi_type, field_1, field_2" so it will order aggregation, after kpi_type, after field_1 and after field_2.

What I am facing is that each order overrides the previous one and not work combined.

2 situation - I would like to order by a field, but I don't want to see the field in the table, it is just a order by. The field is aggregation_type.

Thank you.
Fabio

**Comment by admin-vizcentric** [comment]
Hi @fabiofilz 

Thanks for providing additional information the query is already constructed as per your requirement.

`SELECT country AS country,
       SUM(voucher_amount) AS voucher_discount,
       SUM(transaction_amount) AS transaction_amount,
       SUM(item_quantity) AS item_quantity
FROM transaction_summary
GROUP BY country
ORDER BY voucher_amount DESC,
         transaction_amount DESC,
         item_quantity DESC,
         country DESC
LIMIT 20
OFFSET 0`

**Point 2#**  Currently we can't hide a field that is used for sorting.  I will pass on this requirement to the development team. 

Thanks,
Vizcentric Team

**Comment by fabiofilz** [comment]
Hi @admin-vizcentric,

I have just installed the last version a the order is not working.
Could you please check it?

Kind regards,
Fabio

![image](https://user-images.githubusercontent.com/45266582/79349267-f3471800-7f2d-11ea-8993-ca8be10d4e86.png)

![image](https://user-images.githubusercontent.com/45266582/79349746-88e2a780-7f2e-11ea-919c-f5f0e0412dbf.png)

**Comment by fabiofilz** [comment]
This ticket can be closed
