### ISSUE TITLE
AWS Aurora PostgreSQL-Compatible Edition

### ISSUE THREAD

**Issue by fabiofilz** [viz-centric/flair-bi#581]
Hi Support team,

I hope you are well.

I would like to check if the Postgres data connection of flair-bi is compatible with AWS Aurora PostgreSQL-Compatible Edition.

Kind regards,
Fabio

**Comment by admin-vizcentric** [comment]
Hi @fabiofilz ,

Yes, it's possible to connect to AWS Aurora;  you can use Postgres connector in Flair BI connection wizard to connect to AWS Aurora Postgres. 

If you want to connect to AWS Aurora MySQL use Flair MySQL connector. 

Best Regards,
VizCentric Support

**Comment by fabiofilz** [comment]
Ok, thank you for confirming it.
